<!DOCTYPE html> 
<html>
	<head>
		<title>ThinPHP Admin</title>
		<base href="" />
		<!--link rel="stylesheet" href="css/styles.css" type="text/css" media="screen" /-->
		<!--script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script-->
		<!--script src="js/scripts.js" type="text/javascript"></script-->
	</head>
	<body>

{$content}

	</body>
</html>
